version: '3.7'

networks:
  eai-network:
    driver: bridge
volumes:
  my-datavolume:

services:
  mysql:
    container_name: mysql
    # build: ./docker/mulesoft
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=core
    ports:
      - 3306:3306
    networks:
      - eai-network
    volumes:
      - my-datavolume:/var/lib/mysql
      
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - eai-network
    volumes:
      - my-datavolume:/var/lib/mysql

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=eai
        - RABBITMQ_DEFAULT_PASS=5ZxZ9hMkySW9
    ports:
      - 5672:5672
      - 8090:15672
    networks:
      - eai-network